#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; TMP_WORK_DIR="$2"; REV="$3"

[[ ! -f "$TMP_WORK_DIR/.dokku-pom" ]] && exit

dokku_log_info2 "POM selection plugin detected"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  pom_file="${line[1]}"
  dokku_log_info2 "Creating pom.xml from ./$pom_file"

  # Move the app we want to deploy to a temp directory.
  cp -f "$TMP_WORK_DIR/$pom_file" "$TMP_WORK_DIR/pom.xml"
  exit
done 10<"$TMP_WORK_DIR/.dokku-pom"

dokku_log_info2 "The application $APP is not defined in .dokku-pom!"
exit 1
